---
language: ruby
rvm:
- 2.0.0
- 2.1.5
- 2.2.0
script: bundle exec rake
gemfile:
- gemfiles/activerecord_3.1.gemfile
- gemfiles/activerecord_3.2.gemfile
- gemfiles/activerecord_4.0.gemfile
- gemfiles/activerecord_4.1.gemfile
- gemfiles/activerecord_4.2.gemfile
- gemfiles/rspec_3.0.gemfile
- gemfiles/rspec_3.1.gemfile
- gemfiles/rspec_3.2.gemfile
