sqlite3:
  adapter: sqlite3
  database: ':memory:'
postgresql:
  adapter: postgresql
  encoding: unicode
  database: schema_expectations_test
  username: postgres
mysql2:
  adapter: mysql2
  encoding: utf8
  database: schema_expectations_test
  username: root
